### ISSUE TITLE
Is canonicalization single?

### ISSUE THREAD

**Issue by iherman** [w3c/lds-wg-charter#45]
(Originally raised by @samuelweiler in https://github.com/w3c/strategy/issues/262#issuecomment-822696701; moved here with permission.)

When I think of canonicalization for signing, a key property of the canonicalized form is that there is a _single_ such form - the function always gives the same result.  When I look at [the charter explainer](https://w3c.github.io/lds-wg-charter/explainer.html#canonicalization), that property isn't clear.   Am I just not understanding those words?  Should that language be a little clearer?

**Comment by iherman** [comment]
You are of course right: canonicalization is a _single_ form. 

But... the [§1 of the explainer](https://w3c.github.io/lds-wg-charter/explainer.html#canonicalize) defines:

> RDF Dataset Canonicalization is a function _C_ that maps an RDF Dataset to an RDF Dataset in a manner that…

i.e., it _is_ defined as a function.

Of course there may be several such functions and the goal of the standard is to define either a single function or, most probably a family of functions that is parametrized by the choice of a hashing function for the way it operates.

Can you propose a change on the explainer text that makes this clearer?

**Comment by iherman** [comment]
@samuelweiler I can give you an overly simple example here:

```
_:A <http://example.com/prop1> "Some literal".
```

and

```
_:xyz <http://example.com/prop1> "Some literal".
```

and

```
_:ABCEFG <http://example.com/prop1> "Some literal".
```

are all _isomorphic_ RDF graphs, and there is an infinite number of them:  the subject, in all three, is a blank node, and the label can be just about any string. What canonicalization does is to deterministically calculate a blank node label, starting from any of the forms above, yielding, say, '_:c1234', i.e., generating the graph

```
_:c1234 <http://example.com/prop1> "Some literal".
```

which would be considered the canonical form of those isomorphic graphs.

However, I am a bit uneasy going into the explanation in the charter explainer. I do not think this is the place. There is a reference to [Aidan's paper](http://aidanhogan.com/docs/rdf-canonicalisation.pdf) in the explainer document that gives a good introductory explanation of the problem...

**Comment by samuelweiler** [comment]
> However, I am a bit uneasy going into the explanation in the charter explainer. I do not think this is the place.

Fine.  I defer to your judgement.
