### ISSUE TITLE
Rename "Linked Data Hash" as "RDF Dataset Hash"

### ISSUE THREAD

**Issue by afs** [w3c/lds-wg-charter#63]
The charter has 2 sections - deliverables 1 and 2 are about single RDF Datasets, 3 and 4 about linkages and "Linked Datasets" introduced in item 3 (LDI).

It would be helpful to rename deliverable 2

Linked Data Hash => RDF Dataset Hash (RDH)

to reflect it applies to one dataset and follows on from RDC.

**Comment by iherman** [comment]
Yes, this makes sense. 

I have created a PR (#64); approval/disapproval to be set there...
